### PR TITLE
Added customizable text colors

### PR DESCRIPTION
**Pull request by Kirpal**

### CODE REVIEW

**Comment by dmlapteacru** [comment]
@Kirpal  Great work. Thank you!

**Comment by dmlapteacru** [comment]
@Kirpal do you mind to take a look into other issue that we have here? :D Not sure when I will be able to take a look on it

**Comment by Kirpal** [comment]
If I can find the time I will. Also, I'm just now realizing, I think we should just use  `TextStyle bodyTextStyle` and `TextStyle titleTextStyle` instead of only a few fields. What do you think?

**Comment by dmlapteacru** [comment]
I believe it worth it

**Pull request merged**
